      - name: Install dependencies
        run: flutter pub get

      # ही ओळ नवीन जोडा, ज्यामुळे मिसिंग ॲन्ड्रॉइड फोल्डर आपोआप तयार होईल:
      - name: Create Missing Platforms
        run: flutter create . --platforms=android

      - name: Build APK
        run: flutter build apk --release
        
