- name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4  # इथे v3 ऐवजी v4 केले आहे
        with:
          name: math-elite-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          
